package com.rn00n.inhibitor.application.auth.exception

enum class ErrorCode(
    internal val v1: ErrorCodeV1? = null,
    internal val v2: ErrorCodeV2? = null,
    internal val customError: Int? = null,
    internal val customErrorV2: ErrorCodeV2? = null // customErrorV2 의 경우 HttpStatusCode 는 200 OK 이다.
) {
    // User
    APP_USER_NOT_FOUND(customErrorV2 = ErrorCodeV2.NOT_FOUND),
    INTERNAL_SERVER_ERROR_CUSTOM_ERROR(customError = 500),
    INTERNAL_USER_NOT_FOUND(customError = 404, customErrorV2 = ErrorCodeV2.NOT_FOUND),
    USER_NOT_FOUND(v1 = ErrorCodeV1.USER_NOT_FOUND, v2 = ErrorCodeV2.NOT_FOUND),
    USER_REGISTER_NOT_VALID_EMAIL(v1 = ErrorCodeV1.USER_REGISTER_NOT_VALID_EMAIL, v2 = ErrorCodeV2.INVALID_PARAMETERS),
    USER_REGISTER_NOT_ALLOWED_DOMAIN(v1 = ErrorCodeV1.USER_NOT_ALLOWED_DOMAIN, v2 = ErrorCodeV2.NOT_ALLOWED_EMAIL_DOMAIN),
    USER_REGISTER_DUPLICATE_USERNAME(v1 = ErrorCodeV1.USER_REGISTER_DUPLICATE_USERNAME, v2 = ErrorCodeV2.ALREADY_REGISTERED),
    USER_REGISTER_RESTRICT_SEND_EMAIL(v2 = ErrorCodeV2.NOT_ACCEPTABLE),
    USER_REGISTER_FAILED_UNREGISTERED_USERNAME(v1 = ErrorCodeV1.USER_REGISTER_FAILED_UNREGISTERED_USERNAME),
    USER_REGISTER_FACEBOOK_ALREADY_REGISTERED(
        v1 = ErrorCodeV1.USER_FACEBOOK_ALREADY_REGISTERED,
        v2 = ErrorCodeV2.FACEBOOK_ALREADY_REGISTERED
    ),
    USER_REGISTER_NAVER_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_NAVER_ALREADY_REGISTERED, v2 = ErrorCodeV2.NAVER_ALREADY_REGISTERED),
    USER_REGISTER_TWITTER_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_TWITTER_ALREADY_REGISTERED, v2 = ErrorCodeV2.TWITTER_ALREADY_REGISTERED),
    USER_REGISTER_GOOGLE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_GOOGLE_ALREADY_REGISTERED, v2 = ErrorCodeV2.GOOGLE_ALREADY_REGISTERED),
    USER_REGISTER_APPLE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_APPLE_ALREADY_REGISTERED, v2 = ErrorCodeV2.APPLE_ALREADY_REGISTERED),
    USER_REGISTER_YAHOO_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_YAHOO_ALREADY_REGISTERED, v2 = ErrorCodeV2.YAHOO_ALREADY_REGISTERED),
    USER_REGISTER_LINE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_LINE_ALREADY_REGISTERED, v2 = ErrorCodeV2.LINE_ALREADY_REGISTERED),
    USER_REGISTER_KAKAO_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_KAKAO_ALREADY_REGISTERED, v2 = ErrorCodeV2.KAKAO_ALREADY_REGISTERED),
    USER_REGISTER_MULTI_ACCOUNT_REGISTERED(v1 = ErrorCodeV1.USER_MULTI_ACCOUNT_REGISTERED),
    USER_DEREGISTRER_MEMBERSHIP_USER(v2 = ErrorCodeV2.CANNOT_UNREGISTER_MEMBERSHIP_USER),
    USER_INVALID_PASSWORD_V2(v2 = ErrorCodeV2.INVALID_PASSWORD),
    USER_INCORRECT_PASSWORD(v1 = ErrorCodeV1.USER_INCORRECT_PASSWORD, v2 = ErrorCodeV2.INCORRECT_PASSWORD),
    USER_ALLOWED_DEVICE_NUMBER_EXCEED(v1 = ErrorCodeV1.USER_ALLOWED_DEVICE_NUMBER_EXCEED),
    USER_DEVICE_ALREADY_DEAUTHORIZED(v1 = ErrorCodeV1.USER_DEVICE_ALREADY_DEAUTHORIZED),
    USER_SOCIAL_LOGIN_ONLY(v1 = ErrorCodeV1.USER_SOCIAL_ONLY),
    USER_SOCIAL_CONNECT_ONLY_ONE(v1 = ErrorCodeV1.USER_CAN_CONNECT_ONLY_ONE),
    USER_SOCIAL_ALREADY_CONNECTED_ANOTHER(v1 = ErrorCodeV1.USER_SOCIAL_ALREADY_CONNECTED_ANOTHER),
    USER_SOCIAL_FACEBOOK_LOGIN_FAIL(v1 = ErrorCodeV1.USER_FACEBOOK_LOGIN_FAIL),
    USER_SOCIAL_FACEBOOK_RESPONSE_ERROR(v1 = ErrorCodeV1.USER_FACEBOOK_RESPONSE_ERROR),
    USER_SOCIAL_FACEBOOK_EMAIL_PERMISSION_ERROR(v1 = ErrorCodeV1.USER_FACEBOOK_EMAIL_PERMISSION_ERROR),
    USER_SOCIAL_NAVER_LOGIN_FAIL(v1 = ErrorCodeV1.USER_NAVER_LOGIN_FAIL),
    USER_SOCIAL_TWITTER_LOGIN_FAIL(v1 = ErrorCodeV1.USER_TWITTER_LOGIN_FAIL),
    USER_SOCIAL_GOOGLE_LOGIN_FAIL(v1 = ErrorCodeV1.USER_GOOGLE_LOGIN_FAIL),
    USER_SOCIAL_APPLE_LOGIN_FAIL(v1 = ErrorCodeV1.USER_APPLE_LOGIN_FAIL),
    USER_SOCIAL_YAHOOJAPAN_LOGIN_FAIL(v1 = ErrorCodeV1.USER_YAHOO_LOGIN_FAIL),
    USER_SOCIAL_LINE_LOGIN_FAIL(v1 = ErrorCodeV1.USER_LINE_LOGIN_FAIL),
    USER_SOCIAL_KAKAO_LOGIN_FAIL(v1 = ErrorCodeV1.USER_KAKAO_LOGIN_FAIL),
    USER_KAKAO_RESPONSE_ERROR(v1 = ErrorCodeV1.USER_KAKAO_RESPONSE_ERROR),
    USER_EMAIL_VERIFICATION_NOT_YET(v1 = ErrorCodeV1.USER_VERIFICATION_NOT_YET),
    USER_EMAIL_INVALID_TOKEN(v1 = ErrorCodeV1.USER_INVALID_TOKEN),
    USER_EMAIL_INVALID_EMAIL(v1 = ErrorCodeV1.USER_INVALID_EMAIL, v2 = ErrorCodeV2.INVALID_EMAIL),
    USER_EMAIL_TOKEN_EXPIRED(v2 = ErrorCodeV2.EXPIRED),
    USER_EMAIL_INVALID_TOKEN_V2(v2 = ErrorCodeV2.INVALID_TOKEN_NUMBER),
    USER_EMAIL_DUPLICATED_EMAIL(v2 = ErrorCodeV2.DUPLICATED_EMAIL),
    USER_INVALID_USERNAME_V2(v2 = ErrorCodeV2.INVALID_EMAIL),
    INVALID_PARAMETERS_V2(v2 = ErrorCodeV2.INVALID_PARAMETERS),
    NOT_LOGIN_USER_TO_SEND_SELF_REQUEST(v1 = ErrorCodeV1.NOT_LOGIN_USER_TO_SEND_SELF_REQUEST),
    SOCIAL_ONLY_CONNECTED(v2 = ErrorCodeV2.SOCIAL_ONLY_CONNECTED),
    USER_EMAIL_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_ALREADY_REGISTERED, v2 = ErrorCodeV2.ALREADY_REGISTERED),
    USER_EMAIL_NAVER_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_NAVER_ALREADY_REGISTERED),
    USER_EMAIL_TWITTER_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_TWITTER_ALREADY_REGISTERED),
    USER_EMAIL_FACEBOOK_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_FACEBOOK_ALREADY_REGISTERED),
    USER_EMAIL_YAHOO_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_YAHOO_ALREADY_REGISTERED),
    USER_EMAIL_GOOGLE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_GOOGLE_ALREADY_REGISTERED),
    USER_EMAIL_APPLE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_APPLE_ALREADY_REGISTERED),
    USER_EMAIL_LINE_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_LINE_ALREADY_REGISTERED),
    USER_EMAIL_KAKAO_ALREADY_REGISTERED(v1 = ErrorCodeV1.USER_EMAIL_KAKAO_ALREADY_REGISTERED),
    USER_KAKAO_PHONENUMBER_NOT_SET(v1 = ErrorCodeV1.USER_KAKAO_PHONENUMBER_NOT_SET),
    USER_KAKAO_EMAIL_PERMISSION_ERROR(v1 = ErrorCodeV1.USER_KAKAO_EMAIL_PERMISSION_ERROR),
    ALREADY_ADULT_BLOCKED(v2 = ErrorCodeV2.ALREADY_ADULT_BLOCKED),
    USER_SOCIAL_LOGIN_FAIL(v1 = ErrorCodeV1.USER_SOCIAL_LOGIN_FAIL),
    USER_FACEBOOK_EMAIL_NOT_SET(v1 = ErrorCodeV1.USER_FACEBOOK_EMAIL_NOT_SET),
    USER_TWITTER_EMAIL_NOT_SET(v1 = ErrorCodeV1.USER_TWITTER_EMAIL_NOT_SET),
    USER_KAKAO_EMAIL_NOT_SET(v1 = ErrorCodeV1.USER_KAKAO_EMAIL_NOT_SET),
    USER_LINE_EMAIL_NOT_SET(v1 = ErrorCodeV1.USER_LINE_EMAIL_NOT_SET),
    USER_CERT_ADULT_BLOCKED_FAIL(v1 = ErrorCodeV1.USER_CERT_ADULT_BLOCKED_FAIL),
    USER_NAME_NOT_CHANGED(v2 = ErrorCodeV2.NOT_CHANGED),

    // 시즌그리팅 관련 오류 추가
    ORDERS_NOT_FOUND(v1 = ErrorCodeV1.ORDERS_NOT_FOUND, v2 = ErrorCodeV2.NOT_FOUND),
    NOT_CHANGE_SHIPPING_INFO(v1 = ErrorCodeV1.NOT_CHANGE_SHIPPING_INFO, v2 = ErrorCodeV2.FORBIDDEN),

    // common
    SUCCESS(customError = 200),
    BAD_REQUEST(customError = 400),
    UNAUTHORIZED(customError = 401),
    FORBIDDEN(customError = 403),
    NOT_FOUND(customError = 404),
    INTERNAL_SERVER_ERROR(customError = 500),
    ERROR(customError = 500),
    CONFLICT(v2 = ErrorCodeV2.CONFLICT, customErrorV2 = ErrorCodeV2.CONFLICT),

    // Auth
    INVALID_CLIENT(customError = 401),
    INVALID_GRANT(customError = 400),
    ;

    fun isSuccess(): Boolean {
        return customErrorV2 != null
    }

    fun getCode(): String {
        return when {
            customErrorV2 != null -> customErrorV2.errorNum.toString()
            customError != null -> customError.toString()
            v1 != null -> v1.errorNum
            v2 != null -> v2.errorNum.toString()
            else -> "400"
        }
    }
}

/**
 * Error Code V1.
 */
internal enum class ErrorCodeV1(val errorNum: String, val description: String? = null) {
    GENERAL_DUPLICATE("0002", "이미 등록되었습니다."),

    /* 사용자 관련 1xxx */
    USER_REGISTER_NOT_VALID_EMAIL("1001", "이메일 형식이 맞지 않습니다."),
    USER_REGISTER_DUPLICATE_USERNAME("1002", "이미 가입한 사용자가 있습니다."),
    USER_LOGIN_FAILED("1003", "로그인에 실패하였습니다."),
    USER_REGISTER_FAILED("1004", "회원가입에 실패하였습니다."),
    USER_REREGISTER_FAILED("1005", "탈퇴 회원 복구에 실패하였습니다."),
    USER_REGISTER_FAILED_UNREGISTERED_USERNAME("1006", "탈퇴한 계정입니다."),
    USER_REGISTER_INVALID_PASSWORD("1007", "비밀번호 형식이 맞지 않습니다."),
    USER_NOT_FOUND("1101", "계정을 찾을 수 없습니다."),
    USER_NOT_LOGGED_IN("1102", "로그인이 되어있지 않습니다."),
    USER_RESET_PASSWORD_FAILED("1103", "비밀번호 초기화에 실패하였습니다."),
    USER_INCORRECT_PASSWORD("1104", "비밀번호가 맞지 않습니다."),
    USER_ALLOWED_DEVICE_NUMBER_EXCEED("1105", "동일한 계정으로 로그인 가능한 기기 대수를 초과하였습니다."),
    USER_MULTI_ACCOUNT_REGISTERED("1106", "한 기기에서 여러번 가입하셨습니다. 기존 계정을 이용해주세요."),
    USER_DEVICE_ALREADY_DEAUTHORIZED("1201", "최근에 디바이스 연결 해제를 이미 하였습니다."),
    USER_DEVICE_NOT_AUTHORIZED_ONE("1202", "연결되어 있는 디바이스가 아닙니다."),
    USER_CERT_ADULT_FAIL("1301", "성인인증에 실패하였습니다."),
    USER_CERT_ADULT_BLOCKED_FAIL("1302", "성인인증에 문제가 발생했습니다. 문의해주세요."),
    USER_FACEBOOK_LOGIN_FAIL("1400", "페이스북 로그인에 실패하였습니다."),
    USER_EMAIL_ALREADY_REGISTERED("1401", "이미 이메일로 가입한 사용자입니다."),
    USER_FACEBOOK_ALREADY_REGISTERED("1402", "이미 페이스북으로 가입한 사용자입니다."),
    USER_FACEBOOK_RESPONSE_ERROR("1403", "페이스북 결과 값이 다릅니다."),
    USER_SOCIAL_ONLY("1404", "계정 연결 정보가 하나밖에 없습니다."),
    USER_CONNECTION_NOT_FOUND("1405", "페이스북 연결 정보가 없습니다."),
    USER_FACEBOOK_DEAUTHROIZE_FAIL("1406", "페이스북 deauthorize 에 실패하였습니다."),
    USER_FACEBOOK_EMAIL_PERMISSION_ERROR("1407", "페이스북 이메일 권한이 필요합니다."),
    USER_SOCIAL_ALREADY_CONNECTED_ANOTHER("1408", "다른 계정과 이미 연결되었습니다."),
    USER_FACEBOOK_EMAIL_NOT_SET("1409", "페이스북 이메일 설정을 확인해주세요."),
    USER_NAVER_LOGIN_FAIL("1410", "네이버 로그인에 실패하였습니다."),
    USER_NAVER_RESPONSE_ERROR("1411", "네이버 결과 값이 다릅니다."),
    USER_NAVER_ALREADY_REGISTERED("1412", "이미 네이버로 가입한 사용자입니다."),
    USER_EMAIL_FACEBOOK_ALREADY_REGISTERED("1413", "이메일 또는 페이스북으로 가입된 계정입니다."),
    USER_EMAIL_NAVER_ALREADY_REGISTERED("1414", "이메일 또는 네이버로 가입된 계정입니다"),
    USER_CAN_CONNECT_ONLY_ONE("1415", "이미 다른 수단과 연결되어 있습니다."),
    USER_TWITTER_LOGIN_FAIL("1416", "트위터 로그인에 실패하였습니다."),
    USER_TWITTER_RESPONSE_ERROR("1417", "트위터 결과 값이 다릅니다"),
    USER_TWITTER_ALREADY_REGISTERED("1418", "이미 트위터로 가입한 사용자입니다."),
    USER_EMAIL_TWITTER_ALREADY_REGISTERED("1419", "이메일 또는 트위터로 가입된 계정입니다."),
    USER_SOCIAL_LOGIN_FAIL("1420", "간편 로그인에 실패하였습니다."),
    USER_YAHOO_LOGIN_FAIL("1421", "야후 로그인에 실패하였습니다."),
    USER_YAHOO_RESPONSE_ERROR("1422", "야후 결과 값이 다릅니다"),
    USER_YAHOO_ALREADY_REGISTERED("1423", "이미 야후로 가입한 사용자입니다."),
    USER_EMAIL_YAHOO_ALREADY_REGISTERED("1424", "이메일 또는 야후로 가입된 계정입니다."),
    USER_TWITTER_EMAIL_NOT_SET("1425", "트위터 이메일 설정을 확인해주세요."),
    USER_NOT_ALLOWED_DOMAIN("1426", "허용되지 않는 이메일로 가입을 시도하였습니다."),
    USER_VERIFICATION_NOT_YET("1427", "이메일 검증 프로세스를 진행하지 않았습니다."),
    USER_INVALID_TOKEN("1428", "잘못된 인증 토큰입니다."),
    USER_INVALID_EMAIL("1429", "검증을 통과한 이메일이 아닙니다."),

    USER_GOOGLE_LOGIN_FAIL("1430", "구글 로그인에 실패하였습니다."),
    USER_GOOGLE_RESPONSE_ERROR("1431", "구글 결과 값이 다릅니다."),
    USER_GOOGLE_ALREADY_REGISTERED("1432", "이미 구글로 가입한 사용자입니다."),
    USER_EMAIL_GOOGLE_ALREADY_REGISTERED("1433", "이메일 또는 구글로 가입된 계정입니다"),

    USER_APPLE_LOGIN_FAIL("1434", "애플 로그인에 실패하였습니다."),
    USER_APPLE_RESPONSE_ERROR("1435", "애플 결과 값이 다릅니다."),
    USER_APPLE_ALREADY_REGISTERED("1436", "이미 애플로 가입한 사용자입니다."),
    USER_EMAIL_APPLE_ALREADY_REGISTERED("1437", "이메일 또는 애플로 가입된 계정입니다"),
    USER_LINE_LOGIN_FAIL("1438", "LINE 로그인에 실패하였습니다."),
    USER_LINE_RESPONSE_ERROR("1439", "LINE 결과 값이 다릅니다."),
    USER_LINE_ALREADY_REGISTERED("1440", "이미 LINE으로 가입한 사용자입니다."),
    USER_EMAIL_LINE_ALREADY_REGISTERED("1441", "이메일 또는 LINE으로 가입된 계정입니다"),
    USER_LINE_EMAIL_NOT_SET("1442", "LINE 이메일 설정을 확인해주세요."),

    USER_KAKAO_LOGIN_FAIL("1443", "KAKAO 로그인에 실패하였습니다."),
    USER_KAKAO_RESPONSE_ERROR("1444", "KAKAO 결과 값이 다릅니다."),
    USER_KAKAO_ALREADY_REGISTERED("1445", "이미 KAKAO로 가입한 사용자입니다."),
    USER_EMAIL_KAKAO_ALREADY_REGISTERED("1446", "이메일 또는 KAKAO로 가입된 계정입니다"),
    USER_KAKAO_EMAIL_NOT_SET("1447", "KAKAO 이메일 설정을 확인해주세요."),
    USER_KAKAO_PHONENUMBER_NOT_SET("1448", "KAKAO 휴대폰 설정을 확인해주세요."),
    USER_KAKAO_EMAIL_PERMISSION_ERROR("1449", "KAKAO 프로필, 이메일 그리고 휴대폰 조회 권한이 필요합니다."),

    USER_MYLIST_ITEM_LIMIT_FAIL("1500", "한 리스트에 만화를 20개 이상 넣을 수 없습니다."),
    USER_MYLIST_LIST_LIMIT_FAIL("1501", "리스트는 총 20개까지 생성할 수 있습니다."),

    /* 만화 관련 2xxx */
    EPISODE_VIEW_NOT_ALLOWED("2001", "유료 에피소드는 구매 후에 감상할 수 있습니다."),
    EPISODE_ADULT_NOT_ALLOWED("2002", "해당 에피소드는 성인 인증 후에 감상할 수 있습니다."),

    /* 구매 관련 4xxx */
    /* 구매 일반 40xx */
    PURCHASE_SERVER_ERROR("4000", "구매에 실패하였습니다."),
    PURCHASE_ALREADY_PURCHASED("4001", "이미 구입하셨습니다."),
    PURCHASE_NOT_SUPPORTED_PLATFORM("4002", "지원하지 않는 플랫폼입니다."),
    PURCHASE_NOT_SUPPORTED_PURCHASE_TYPE("4003", "지원하지 않는 타입입니다."),
    PURCHASE_NOT_CHARGED_COIN("4004", "코인 잔액이 부족합니다."),
    PURCHASE_NOT_CHARGED_POINT("4005", "포인트 잔액이 부족합니다."),
    PURCHASE_INVALID_PRICE("4006", "요청한 금액이 다릅니다."),
    PURCHASE_INVALID_PURCHASE_TYPE("4007", "완결된 만화가 아닙니다."),
    PURCHASE_PERMISSION_ERROR("4008", "구매할 수 없습니다."),

    /* 구매 쿠폰 41xx */
    PURCHASE_COUPON_NOT_FOUND("4100", "쿠폰을 찾을 수 없습니다."),
    PURCHASE_COUPON_ALREADY_USED("4101", "이미 사용한 쿠폰입니다."),
    PURCHASE_COUPON_EXPIRED("4102", "만료된 쿠폰입니다."),
    PURCHASE_COUPON_USE_EXEED("4103", "동일한 쿠폰을 사용하셔서 더이상 사용하실 수 없습니다."),
    PURCHASE_COUPON_BANNED("4104", "쿠폰입력이 제한된 상태입니다."),
    PURCHASE_COUPON_USER_BANNED("4105", "잘못된 쿠폰입력 제한을 초과해 계정이 비활성화되었습니다."),
    PURCHASE_COUPON_UNKNOWN("4106", "요청한 작업을 처리할 수 없습니다."),

    /* 결제 관련 42xx */
    PAYMENT_SERVER_ERROR("4200", "코인 충전을 실패하였습니다."),
    PAYMENT_DUPLICATE_ORDER_ERROR("4201", "이미 결제한 주문 번호입니다."),
    PAYMENT_SIGNATURE_NOT_MATCHED("4202", "서명 검증에 실패하였습니다."),
    PAYMENT_INVALID_INPUT_PARAMETER("4203", "데이터 형식이 맞지 않습니다."),
    PAYMENT_NOT_APPROVED("4204", "승인되지 않은 결제건입니다."),
    PAYMENT_NOT_VALID_RESERVE("4205", "예약이 올바르지 않습니다."),
    PAYMENT_NOT_FOUND_USER("4206", "사용자를 찾을 수 없습니다."),
    PAYMENT_NOT_FOUND_PRODUCT("4207", "해당 상품을 찾을 수 없습니다."),
    PAYMENT_NOT_FOUND_PAYMENT_RECEIPT("4208", "결제 내역을 찾을 수 없습니다."),
    PAYMENT_APPSTORE_SYSTEM_ERROR("4209", "앱스토어 오류로 코인 충전에 실패하였습니다."),

    /* 플레이 관련 5xxx */
    PLAYER_NOT_FOUND("5001", "플레이어를 찾을 수 없습니다."),
    PLAYER_REGISTER_DUPLICATE_USERNAME("5002", "이미 가입한 플레이어가 있습니다."),
    PLAY_KEY_NOT_VALID("5401", "유효하지 않은 Play Key 입니다."),

    /* 태그 관련 6xxx */
    TAG_DUPLICATE("6002", "이미 등록된 태그입니다."),

    /* 시즌그리팅 관련 7xxx */
    ORDERS_NOT_FOUND("7001", "주문을 찾을 수 없습니다."),
    NOT_CHANGE_SHIPPING_INFO("7002", "배송지 수정가능일자가 지났습니다."),

    /* 락스크린 Lxxx */
    LOCKSCREEN_DUPLECATED("LOCKSCREEN_0002", "중복된 데이터입니다."),
    LOCKSCREEN_INVALID_IMAGE_TYPE("L001", "지원하지 않는 이미지 타입입니다."),
    LOCKSCREEN_NOT_FOUND_IMAGE("L002", "이미지를 찾을 수 없습니다."),
    LOCKSCREEN_UNAUTHORIZED_IMAGE("L003", "해당 이미지를 보시려면 레진코믹스 로그인을 해주세요."),

    /* 관리자용 사용자 관련 A1xx */
    ADMIN_USER_HAS_BALANCE("A101", "사용자가 잔액을 보유하고 있습니다."),

    /* 관리자용 쿠폰 A41x */
    ADMIN_INVALID_PARAMETER_ISSUE_COUPON("A410", "발행 쿠폰 파라미터가 올바르지 않습니다."),
    NOT_LOGIN_USER_TO_SEND_SELF_REQUEST("1438", "only the login user can request for self."),
}

/**
 * Error Code V2.
 */
enum class ErrorCodeV2(val errorNum: Int, val isError: Boolean? = false) {
    UNKNOWN(0, true),
    SUCCESS(200),
    BAD_REQUEST(400, true),
    UNAUTHORIZED(401),
    PAYMENT_REQUIRED(402),
    FORBIDDEN(403),
    NOT_FOUND(404),
    NOT_ALLOWED_EMAIL_DOMAIN(405),
    NOT_ACCEPTABLE(406),
    CONFLICT(409, true),
    UNSUPPORTED_LOCALE(419),
    INVALID_LOCALE(420),
    INVALID_URL(421),
    INVALID_PARAMETERS(422),
    TOO_MANY_REQUESTS(429),
    INTERNAL_SERVER_ERROR(500, true),
    INVALID_EMAIL(601),
    DUPLICATED_EMAIL(602),
    INCORRECT_PASSWORD(603),
    NOT_FOUND_RESETKEY(604),
    SOCIAL_ONLY_CONNECTED(605),
    USER_META_NOT_INITIATED_YET(606),
    ALREADY_REGISTERED(607),
    NOT_CHANGED(608),
    INVALID_PASSWORD(609),
    CANNOT_UNREGISTER_MEMBERSHIP_USER(610),
    SESSION_PURCHASE_ERROR(611),
    NOT_ENOUGH(612),
    NO_NEED(613),
    ALREADY_REFUNDED(614),
    NON_REFUNDABLE(615),
    EXPIRED(616),
    ALREADY_CHARGED(617),
    PAYMENT_PG_AUTHORIZE_USER_ERROR(618),
    PAYMENT_PG_CONFIRM_ERROR(619),
    PAYMENT_PG_CANCEL_ERROR(620),
    PAYMENT_PG_OCB_PASSWORD_ERROR_EXCEED(621),
    PAYMENT_PG_OCB_PASSWORD_ERROR(622),
    INVALID_TOKEN_NUMBER(670),
    FACEBOOK_ALREADY_REGISTERED(671),
    TWITTER_ALREADY_REGISTERED(672),
    NAVER_ALREADY_REGISTERED(673),
    YAHOO_ALREADY_REGISTERED(674),
    GOOGLE_ALREADY_REGISTERED(675),
    APPLE_ALREADY_REGISTERED(676),
    LINE_ALREADY_REGISTERED(677),
    KAKAO_ALREADY_REGISTERED(678),
    ALREADY_ADULT_BLOCKED(1302),
}
